stages:
  download:
    cmd: python src/data/download.py
    deps:
    - src/data/download.py
    outs:
    - data/raw
  preprocess:
    cmd: python src/data/preprocess.py
    deps:
    - data/raw
    - src/data/preprocess.py
    outs:
    - data/processed
  train:
    cmd: python src/models/train.py
    deps:
    - data/processed
    - src/models/train.py
    outs:
    - models/rfr_best_model.pkl
